//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Viktor Login.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShortDB) DeepCopyInto(out *ShortDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShortDB.
func (in *ShortDB) DeepCopy() *ShortDB {
	if in == nil {
		return nil
	}
	out := new(ShortDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShortDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShortDBHeartBeat) DeepCopyInto(out *ShortDBHeartBeat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShortDBHeartBeat.
func (in *ShortDBHeartBeat) DeepCopy() *ShortDBHeartBeat {
	if in == nil {
		return nil
	}
	out := new(ShortDBHeartBeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShortDBKeepAlive) DeepCopyInto(out *ShortDBKeepAlive) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShortDBKeepAlive.
func (in *ShortDBKeepAlive) DeepCopy() *ShortDBKeepAlive {
	if in == nil {
		return nil
	}
	out := new(ShortDBKeepAlive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShortDBList) DeepCopyInto(out *ShortDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShortDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShortDBList.
func (in *ShortDBList) DeepCopy() *ShortDBList {
	if in == nil {
		return nil
	}
	out := new(ShortDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShortDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShortDBSpec) DeepCopyInto(out *ShortDBSpec) {
	*out = *in
	if in.HeartBeat != nil {
		in, out := &in.HeartBeat, &out.HeartBeat
		*out = new(ShortDBHeartBeat)
		**out = **in
	}
	if in.Keepalive != nil {
		in, out := &in.Keepalive, &out.Keepalive
		*out = new(ShortDBKeepAlive)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShortDBSpec.
func (in *ShortDBSpec) DeepCopy() *ShortDBSpec {
	if in == nil {
		return nil
	}
	out := new(ShortDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShortDBStatus) DeepCopyInto(out *ShortDBStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShortDBStatus.
func (in *ShortDBStatus) DeepCopy() *ShortDBStatus {
	if in == nil {
		return nil
	}
	out := new(ShortDBStatus)
	in.DeepCopyInto(out)
	return out
}
