// Code generated by protoc-gen-rich-model. DO NOT EDIT.
// versions:
// - protoc-gen-rich-model v1.1.1
// - protoc             v5.26.1
// source: fixtures/link.proto

package fixtures

// Link list
type links struct {
	// Links
	link []*link
}

// GetLink returns the value of the link field.
func (m *links) GetLink() []*link {
	return m.link
}
