// Code generated by protoc-gen-rich-model. DO NOT EDIT.
// versions:
// - protoc-gen-rich-model v1.0.0
// - protoc             v5.26.1
// source: fixtures/link.proto

package fixtures

import (
	"google.golang.org/protobuf/types/known/fieldmaskpb"
	"time"
)

type link struct {
	fieldmask fieldmaskpb.FieldMask
	url       string
	hash      string
	describe  string
	createdat time.Time
	updatedat time.Time
}
