# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/domain/referral/v1/queries.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$src/domain/referral/v1/queries.proto\x12\x16src.domain.referral.v1\"\"\n\x10ReferralGetQuery\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\",\n\x11ReferralListQuery\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId*`\n\rReferralQuery\x12\x1e\n\x1aREFERRAL_QUERY_UNSPECIFIED\x10\x00\x12\x16\n\x12REFERRAL_QUERY_GET\x10\x01\x12\x17\n\x13REFERRAL_QUERY_LIST\x10\x02\x42\xa5\x01\n\x1a\x63om.src.domain.referral.v1B\x0cQueriesProtoP\x01\xa2\x02\x03SDR\xaa\x02\x16Src.Domain.Referral.V1\xca\x02\x16Src\\Domain\\Referral\\V1\xe2\x02\"Src\\Domain\\Referral\\V1\\GPBMetadata\xea\x02\x19Src::Domain::Referral::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.domain.referral.v1.queries_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.src.domain.referral.v1B\014QueriesProtoP\001\242\002\003SDR\252\002\026Src.Domain.Referral.V1\312\002\026Src\\Domain\\Referral\\V1\342\002\"Src\\Domain\\Referral\\V1\\GPBMetadata\352\002\031Src::Domain::Referral::V1'
  _globals['_REFERRALQUERY']._serialized_start=146
  _globals['_REFERRALQUERY']._serialized_end=242
  _globals['_REFERRALGETQUERY']._serialized_start=64
  _globals['_REFERRALGETQUERY']._serialized_end=98
  _globals['_REFERRALLISTQUERY']._serialized_start=100
  _globals['_REFERRALLISTQUERY']._serialized_end=144
# @@protoc_insertion_point(module_scope)
