{
 "title": "Postgres (ShortLink)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pg_users",
    "label": "users",
    "query": "SELECT usename AS \"User\" FROM pg_user;"
   }
  ]
 },
 "panels": [
  { "title": "Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shared preload libraries",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT trim(unnest(string_to_array(current_setting('shared_preload_libraries'), ','))) AS \"Shared Preload Library\"\nFROM (SELECT current_setting('shared_preload_libraries')) AS t;\n"
    }
   ]
  },
  {
   "title": "Connects",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT count(*), state\nFROM pg_stat_activity\nGROUP BY 2;"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Longest queries",
   "type": "table",
   "description": "query the 10 longest-running queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "-- query the 10 longest running queries\nWITH statements AS (\n    SELECT * FROM pg_stat_statements pss\n                      JOIN pg_roles pr ON (userid=oid)\n    WHERE rolname = '$pg_users'\n)\nSELECT calls,\n       query,\n       shared_blks_hit,\n       shared_blks_read,\n       shared_blks_hit/(shared_blks_hit+shared_blks_read)::NUMERIC*100 hit_cache_ratio\nFROM statements\nWHERE calls > 500\n  AND shared_blks_hit > 0\nORDER BY calls DESC, hit_cache_ratio ASC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Index stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT schemaname || '.' || relname AS table,\n       indexrelname AS index,\n       pg_size_pretty(pg_relation_size(i.indexrelid)) AS \"index size\",\n       idx_scan as \"index scans\"\nFROM pg_stat_user_indexes ui\nJOIN pg_index i ON ui.indexrelid = i.indexrelid\nWHERE NOT indisunique\n  AND idx_scan < 50\n  AND pg_relation_size(relid) > 5 * 8192\nORDER BY\n  pg_relation_size(i.indexrelid) / nullif(idx_scan, 0) DESC NULLS FIRST,\n  pg_relation_size(i.indexrelid) DESC;"
    }
   ]
  }
 ]
}