// LINK FETCH SINGLE
export const LINK_FETCH_REQUESTED = 'LINK_FETCH_REQUESTED'
export const LINK_FETCH_SUCCEEDED = 'LINK_FETCH_SUCCEEDED'
export const LINK_FETCH_FAILED = 'LINK_FETCH_FAILED'

// LINK FETCH LIST
export const LINK_FETCH_LIST_REQUESTED = 'LINK_FETCH_LIST_REQUESTED'
export const LINK_FETCH_LIST_SUCCEEDED = 'LINK_FETCH_LIST_SUCCEEDED'
export const LINK_FETCH_LIST_FAILED = 'LINK_FETCH_LIST_FAILED'

// LINK CREATE
export const LINK_ADD_REQUESTED = 'LINK_ADD_REQUESTED'
export const LINK_ADD_SUCCEEDED = 'LINK_ADD_SUCCEEDED'
export const LINK_ADD_FAILED = 'LINK_ADD_FAILED'

// LINK UPDATE
export const LINK_UPDATE_REQUESTED = 'LINK_UPDATE_REQUESTED'
export const LINK_UPDATE_SUCCEEDED = 'LINK_UPDATE_SUCCEEDED'
export const LINK_UPDATE_FAILED = 'LINK_UPDATE_FAILED'

// LINK DELETE
export const LINK_DELETE_REQUESTED = 'LINK_DELETE_REQUESTED'
export const LINK_DELETE_SUCCEEDED = 'LINK_DELETE_SUCCEEDED'
export const LINK_DELETE_FAILED = 'LINK_DELETE_FAILED'
