// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"context"
	"github.com/batazor/shortlink/internal/pkg/db"
	"github.com/batazor/shortlink/internal/pkg/logger"
	"github.com/batazor/shortlink/internal/pkg/mq"
	"github.com/batazor/shortlink/internal/pkg/notify"
	"github.com/batazor/shortlink/internal/services/metadata/application"
	"github.com/batazor/shortlink/internal/services/metadata/domain"
	"github.com/batazor/shortlink/internal/services/metadata/infrastructure/mq"
	"github.com/batazor/shortlink/internal/services/metadata/infrastructure/rpc"
	"github.com/batazor/shortlink/internal/services/metadata/infrastructure/store"
	"github.com/batazor/shortlink/pkg/rpc"
	"github.com/google/wire"
)

// Injectors from di.go:

func InitializeMetaDataService(ctx context.Context, runRPCServer *rpc.RPCServer, log logger.Logger, db2 *db.Store, mq2 mq.MQ) (*MetaDataService, func(), error) {
	metaStore, err := NewMetaDataStore(ctx, log, db2)
	if err != nil {
		return nil, nil, err
	}
	service, err := NewMetaDataApplication(metaStore)
	if err != nil {
		return nil, nil, err
	}
	event, err := InitLinkMQ(ctx, log, mq2)
	if err != nil {
		return nil, nil, err
	}
	metadata, err := NewMetaDataRPCServer(runRPCServer, service, log)
	if err != nil {
		return nil, nil, err
	}
	metaDataService, err := NewMetaDataService(log, service, event, metadata, metaStore)
	if err != nil {
		return nil, nil, err
	}
	return metaDataService, func() {
	}, nil
}

// di.go:

type MetaDataService struct {
	Logger logger.Logger

	// Delivery
	linkMQ            *api_mq.Event
	metadataRPCServer *metadata_rpc.Metadata

	// Application
	service *metadata.Service

	// Repository
	metadataStore *meta_store.MetaStore
}

// MetaDataService =====================================================================================================
var MetaDataSet = wire.NewSet(

	InitLinkMQ,
	NewMetaDataRPCServer,

	NewMetaDataApplication,

	NewMetaDataStore,

	NewMetaDataService,
)

func InitLinkMQ(ctx context.Context, log logger.Logger, mq2 mq.MQ) (*api_mq.Event, error) {
	linkMQ := &api_mq.Event{
		MQ: mq2,
	}
	notify.Subscribe(domain.METHOD_ADD, linkMQ)

	return linkMQ, nil
}

func NewMetaDataStore(ctx context.Context, logger2 logger.Logger, db2 *db.Store) (*meta_store.MetaStore, error) {
	store := &meta_store.MetaStore{}
	metadataStore, err := store.Use(ctx, logger2, db2)
	if err != nil {
		return nil, err
	}

	return metadataStore, nil
}

func NewMetaDataApplication(store *meta_store.MetaStore) (*metadata.Service, error) {
	metadataService, err := metadata.New(store)
	if err != nil {
		return nil, err
	}

	return metadataService, nil
}

func NewMetaDataRPCServer(runRPCServer *rpc.RPCServer, application *metadata.Service, log logger.Logger) (*metadata_rpc.Metadata, error) {
	metadataRPCServer, err := metadata_rpc.New(runRPCServer, application, log)
	if err != nil {
		return nil, err
	}

	return metadataRPCServer, nil
}

func NewMetaDataService(
	log logger.Logger,

	service *metadata.Service,

	linkMQ *api_mq.Event,
	metadataRPCServer *metadata_rpc.Metadata,

	metadataStore *meta_store.MetaStore,
) (*MetaDataService, error) {
	return &MetaDataService{
		Logger: log,

		service: service,

		linkMQ:            linkMQ,
		metadataRPCServer: metadataRPCServer,

		metadataStore: metadataStore,
	}, nil
}
