// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"context"
	"github.com/batazor/shortlink/internal/pkg/db"
	"github.com/batazor/shortlink/internal/pkg/logger"
	"github.com/batazor/shortlink/internal/services/metadata/application"
	"github.com/batazor/shortlink/internal/services/metadata/infrastructure/rpc"
	"github.com/batazor/shortlink/internal/services/metadata/infrastructure/store"
	"github.com/batazor/shortlink/pkg/rpc"
	"github.com/google/wire"
)

// Injectors from di.go:

func InitializeMetaDataService(ctx context.Context, runRPCServer *rpc.RPCServer, log logger.Logger, db2 *db.Store) (*MetaDataService, func(), error) {
	metaStore, err := NewMetaDataStore(ctx, log, db2)
	if err != nil {
		return nil, nil, err
	}
	service, err := NewMetaDataApplication(metaStore)
	if err != nil {
		return nil, nil, err
	}
	metadata, err := NewMetaDataRPCServer(runRPCServer, service, log)
	if err != nil {
		return nil, nil, err
	}
	metaDataService, err := NewMetaDataService(log, metadata, metaStore, service)
	if err != nil {
		return nil, nil, err
	}
	return metaDataService, func() {
	}, nil
}

// di.go:

type MetaDataService struct {
	Logger logger.Logger

	// Delivery
	metadataRPCServer *metadata_rpc.Metadata

	// Application
	service *metadata.Service

	// Repository
	metadataStore *meta_store.MetaStore
}

// MetaDataService =====================================================================================================
var MetaDataSet = wire.NewSet(

	NewMetaDataRPCServer,

	NewMetaDataApplication,

	NewMetaDataStore,

	NewMetaDataService,
)

func NewMetaDataStore(ctx context.Context, logger2 logger.Logger, db2 *db.Store) (*meta_store.MetaStore, error) {
	store := &meta_store.MetaStore{}
	metadataStore, err := store.Use(ctx, logger2, db2)
	if err != nil {
		return nil, err
	}

	return metadataStore, nil
}

func NewMetaDataApplication(store *meta_store.MetaStore) (*metadata.Service, error) {
	metadataService, err := metadata.New(store)
	if err != nil {
		return nil, err
	}

	return metadataService, nil
}

func NewMetaDataRPCServer(runRPCServer *rpc.RPCServer, application *metadata.Service, log logger.Logger) (*metadata_rpc.Metadata, error) {
	metadataRPCServer, err := metadata_rpc.New(runRPCServer, application, log)
	if err != nil {
		return nil, err
	}

	return metadataRPCServer, nil
}

func NewMetaDataService(
	log logger.Logger,
	metadataRPCServer *metadata_rpc.Metadata,
	metadataStore *meta_store.MetaStore,
	service *metadata.Service,
) (*MetaDataService, error) {
	return &MetaDataService{
		Logger:            log,
		metadataRPCServer: metadataRPCServer,
		metadataStore:     metadataStore,
		service:           service,
	}, nil
}
