allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  '@tailwindcss/oxide': true
  core-js: true
  cypress: false
  esbuild: true
  protobufjs: true
  rollup: false
  sharp: false
  tldjs: true

autoInstallPeers: true
strictPeerDependencies: false
preferOffline: true
