{
 "title": "PgBouncer",
 "description": "A visual representation of Prometheus metrics collected from PgBouncer servers.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "db",
    "query": "label_values(pgbouncer_databases_current_connections,database)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Client active connections $db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"$db\"})"
    }
   ]
  },
  {
   "title": "Stats queries total $db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( sum (pgbouncer_stats_queries_pooled_total{database=~\"$db\"} ) )"
    }
   ]
  },
  {
   "title": "Database pool size.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_databases_pool_size{database=~\"$db\"})",
     "legendFormat": "{{database}},{{service}}"
    }
   ]
  },
  {
   "title": "Databases reserve pool size.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(pgbouncer_databases_reserve_pool{database=~\"$db\"}[30m]))",
     "legendFormat": "{{database}},{{service}}"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_duration_seconds_total{database=\"$db\"}[30m]) ) )",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Stats queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_duration_seconds_total{database=~\"$db\"}[30m]) ) )",
     "legendFormat": "Duration microseconds"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_pools_client_maxwait_seconds{database=~\"$db\"}[30m]) ) ) ",
     "legendFormat": "Waiting duration microseconds"
    }
   ]
  },
  {
   "title": "Transactions stats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_server_in_transaction_seconds{database=~\"$db\"}[30m]) ) )  ",
     "legendFormat": "Transactions duration microseconds"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_sql_transactions_pooled_total{database=~\"$db\"}[30m]) ) )",
     "legendFormat": "Transactions total"
    }
   ]
  },
  {
   "title": "Pools Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{database=~\"$db\"}",
     "legendFormat": "Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$db\"}",
     "legendFormat": "Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_connections{database=~\"$db\"}",
     "legendFormat": "Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{database=~\"$db\"}",
     "legendFormat": "Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{database=~\"$db\"}",
     "legendFormat": "Server used connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{database=~\"$db\"}",
     "legendFormat": "Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{database=~\"$db\"}",
     "legendFormat": "Server login connections"
    },
    {
     "expr": "pgbouncer_databases_current_connections{database=~\"$db\"}",
     "legendFormat": "Database current connections"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_received_bytes_total{database=~\"$db\"}[30m])*8 ) )",
     "legendFormat": "Received bytes total"
    },
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_sent_bytes_total{database=~\"$db\"}[30m])*8 ) )",
     "legendFormat": "Sent bytes total"
    }
   ]
  }
 ]
}