// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package crud

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LinkLink struct {
	ID        pgtype.UUID
	Url       string
	Hash      string
	Describe  string
	Json      interface{}
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// CQRS for links
type LinkLinkView struct {
	ID              pgtype.UUID
	Url             string
	Hash            interface{}
	Describe        pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ImageUrl        pgtype.Text
	MetaDescription pgtype.Text
	MetaKeywords    pgtype.Text
}
