// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
// - protoc-gen-go-orm v1.5.0
// - protoc             (unknown)
// source: domain/link/v1/link.proto

package filter

import (
	domain "github.com/shortlink-org/shortlink/boundaries/link/link/domain/link/v1"
)

type FilterLink domain.FilterLink

func NewFilter(params *domain.FilterLink) *FilterLink {
	return &FilterLink{
		Url:       params.Url,
		Hash:      params.Hash,
		Describe:  params.Describe,
		CreatedAt: params.CreatedAt,
		UpdatedAt: params.UpdatedAt,
	}
}
