// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package metadata_di

import (
	"context"
	message2 "github.com/ThreeDotsLabs/watermill/message"
	"github.com/google/wire"
	"github.com/shortlink-org/go-sdk/auth/permission"
	"github.com/shortlink-org/go-sdk/cache"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/context"
	"github.com/shortlink-org/go-sdk/cqrs/bus"
	"github.com/shortlink-org/go-sdk/cqrs/message"
	"github.com/shortlink-org/go-sdk/db"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/flight_trace"
	"github.com/shortlink-org/go-sdk/grpc"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/go-sdk/s3"
	"github.com/shortlink-org/go-sdk/watermill"
	"github.com/shortlink-org/go-sdk/watermill/backends/kafka"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/infrastructure/cqrs"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/infrastructure/mq"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/infrastructure/repository/media"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/infrastructure/repository/store"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/infrastructure/rpc/metadata/v1"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/usecases/metadata"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/usecases/parsers"
	"github.com/shortlink-org/shortlink/boundaries/metadata/internal/usecases/screenshot"
	"go.opentelemetry.io/otel/metric"
	metric2 "go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

func InitializeMetaDataService() (*MetaDataService, func(), error) {
	context, cleanup, err := ctx.New()
	if err != nil {
		return nil, nil, err
	}
	configConfig, err := config.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerLogger, cleanup2, err := logger.NewDefault(context, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := tracing.New(context, loggerLogger, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := metrics.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := profiling.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	recorder, err := flight_trace.New(context, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	meterProvider := monitoring.Metrics
	dbDB, err := db.New(context, loggerLogger, tracerProvider, meterProvider, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	metaStore, err := NewMetaDataStore(context, loggerLogger, dbDB)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	backend, err := kafka.New(context, loggerLogger, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := _wireValue
	client, err := watermill.New(context, loggerLogger, configConfig, backend, meterProvider, tracerProvider, v...)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	publisher := client.Publisher
	namer := cqrs.NewShortlinkNamer()
	protoMarshaler := cqrs.NewProtoMarshaler(namer)
	eventBus, err := cqrs.NewEventBus(publisher, protoMarshaler, namer)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uc, err := NewParserUC(metaStore, eventBus, loggerLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	subscriber := client.Subscriber
	s3Client, err := s3.New(context, loggerLogger, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service, err := NewMetaDataMediaStore(context, s3Client)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	screenshotUC, err := NewScreenshotUC(context, service)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	metadataUC, err := NewMetadataUC(loggerLogger, uc, screenshotUC, eventBus)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	typeRegistry, err := cqrs.NewEventRegistry()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	event, err := InitMetadataMQ(context, loggerLogger, subscriber, metadataUC, typeRegistry, protoMarshaler)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registry := monitoring.Prometheus
	server, err := grpc.InitServer(context, loggerLogger, tracerProvider, registry, recorder, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	metadata, err := NewMetaDataRPCServer(loggerLogger, server, uc, screenshotUC, metadataUC)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	metaDataService, err := NewMetaDataService(loggerLogger, configConfig, monitoring, tracerProvider, pprofEndpoint, recorder, uc, event, metadata, metaStore)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return metaDataService, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireValue = []watermill.Option{}
)

// wire.go:

type MetaDataService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Metrics       *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint
	FlightTrace   *flight_trace.Recorder

	// Delivery
	metadataMQ        *metadata_mq.Event
	metadataRPCServer *v1.Metadata

	// Application
	service *parsers.UC

	// Repository
	metadataStore *storeRepository.MetaStore
}

// DefaultSet ==========================================================================================================
var DefaultSet = wire.NewSet(ctx.New, flags.New, config.New, logger.NewDefault, tracing.New, metrics.New, cache.New, profiling.New, flight_trace.New)

// CQRSSet =============================================================================================================
// CQRS wire set for event-driven architecture components
// Provides: EventRegistry, ShortlinkNamer, ProtoMarshaler, EventBus, CommandBus
// Requires: message.Publisher (from watermill.Client)
// Note: ShortlinkNamer is a singleton to ensure consistent naming across all components
var CQRSSet = wire.NewSet(cqrs.NewEventRegistry, cqrs.NewShortlinkNamer, cqrs.NewProtoMarshaler, wire.Bind(new(message.Marshaler), new(*message.ProtoMarshaler)), cqrs.NewEventBus, cqrs.NewCommandBus)

// MetaDataService =====================================================================================================
var MetaDataSet = wire.NewSet(
	DefaultSet, permission.New, wire.FieldsOf(new(*metrics.Monitoring), "Prometheus", "Metrics"), wire.Bind(new(metric.MeterProvider), new(*metric2.MeterProvider)), db.New, wire.Bind(new(watermill.Backend), new(*kafka.Backend)), kafka.New, wire.Value([]watermill.Option{}), watermill.New, wire.FieldsOf(new(*watermill.Client), "Publisher", "Subscriber"), grpc.InitServer, s3.New, CQRSSet,

	InitMetadataMQ,
	NewMetaDataRPCServer,

	NewParserUC,
	NewScreenshotUC,
	NewMetadataUC,

	NewMetaDataStore,
	NewMetaDataMediaStore,

	NewMetaDataService,
)

func InitMetadataMQ(ctx2 context.Context,

	log logger.Logger,
	subscriber message2.Subscriber,
	metadataUC *metadata.UC,
	registry *bus.TypeRegistry,
	marshaler message.Marshaler,
) (*metadata_mq.Event, error) {
	metadataMQ, err := metadata_mq.New(subscriber, metadataUC)
	if err != nil {
		return nil, err
	}

	if err := metadataMQ.SubscribeLinkCreated(ctx2, log, registry, marshaler); err != nil {
		return nil, err
	}

	return metadataMQ, nil
}

func NewMetaDataStore(ctx2 context.Context, log logger.Logger, db2 db.DB) (*storeRepository.MetaStore, error) {
	store := &storeRepository.MetaStore{}
	metadataStore, err := store.Use(ctx2, log, db2)
	if err != nil {
		return nil, err
	}

	return metadataStore, nil
}

func NewMetaDataMediaStore(ctx2 context.Context, s3_2 *s3.Client) (*s3Repository.Service, error) {
	client, err := s3Repository.New(ctx2, s3_2)
	if err != nil {
		return nil, err
	}

	return client, nil
}

func NewParserUC(store *storeRepository.MetaStore, eventBus *bus.EventBus, log logger.Logger) (*parsers.UC, error) {
	metadataService, err := parsers.New(store, eventBus, log)
	if err != nil {
		return nil, err
	}

	return metadataService, nil
}

func NewScreenshotUC(ctx2 context.Context, media *s3Repository.Service) (*screenshot.UC, error) {
	metadataService, err := screenshot.New(ctx2, media)
	if err != nil {
		return nil, err
	}

	return metadataService, nil
}

func NewMetadataUC(log logger.Logger, parsersUC *parsers.UC, screenshotUC *screenshot.UC, eventBus *bus.EventBus) (*metadata.UC, error) {
	metadataService, err := metadata.New(log, parsersUC, screenshotUC, eventBus)
	if err != nil {
		return nil, err
	}

	return metadataService, nil
}

func NewMetaDataRPCServer(log logger.Logger, runRPCServer *grpc.Server, parsersUC *parsers.UC, screenshotUC *screenshot.UC, metadataUC *metadata.UC) (*v1.Metadata, error) {
	metadataRPCServer, err := v1.New(log, runRPCServer, parsersUC, screenshotUC, metadataUC)
	if err != nil {
		return nil, err
	}

	return metadataRPCServer, nil
}

func NewMetaDataService(

	log logger.Logger, config2 *config.Config, metrics2 *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint,
	flightTrace *flight_trace.Recorder,

	service *parsers.UC,

	metadataMQ *metadata_mq.Event,
	metadataRPCServer *v1.Metadata,

	metadataStore *storeRepository.MetaStore,
) (*MetaDataService, error) {
	return &MetaDataService{

		Log:    log,
		Config: config2,

		Tracer:        tracer,
		Metrics:       metrics2,
		PprofEndpoint: pprofHTTP,
		FlightTrace:   flightTrace,

		service: service,

		metadataMQ:        metadataMQ,
		metadataRPCServer: metadataRPCServer,

		metadataStore: metadataStore,
	}, nil
}
