' C4-PlantUML
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' Components
!define actors https://raw.githubusercontent.com/shortlink-org/shortlink/main/docs/c4/containers/actors
!define ui https://raw.githubusercontent.com/shortlink-org/shortlink/main/docs/c4/containers/ui
!define services https://raw.githubusercontent.com/shortlink-org/shortlink/main/docs/c4/containers/services
!define boundaries https://raw.githubusercontent.com/shortlink-org/shortlink/main/docs/c4/containers/boundaries

' Style
!include https://raw.githubusercontent.com/shortlink-org/shortlink/main/docs/c4/containers/preset/style.puml
