// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/link/link.proto

package link

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Link struct {
	// URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Hash by URL + salt
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// Describe of link
	Describe string `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`
	// Create at
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Update at
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_16115bece156ada2, []int{0}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Link) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Link) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

func (m *Link) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Link) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Links struct {
	Link                 []*Link  `protobuf:"bytes,1,rep,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Links) Reset()         { *m = Links{} }
func (m *Links) String() string { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()    {}
func (*Links) Descriptor() ([]byte, []int) {
	return fileDescriptor_16115bece156ada2, []int{1}
}

func (m *Links) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Links.Unmarshal(m, b)
}
func (m *Links) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Links.Marshal(b, m, deterministic)
}
func (m *Links) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Links.Merge(m, src)
}
func (m *Links) XXX_Size() int {
	return xxx_messageInfo_Links.Size(m)
}
func (m *Links) XXX_DiscardUnknown() {
	xxx_messageInfo_Links.DiscardUnknown(m)
}

var xxx_messageInfo_Links proto.InternalMessageInfo

func (m *Links) GetLink() []*Link {
	if m != nil {
		return m.Link
	}
	return nil
}

func init() {
	proto.RegisterType((*Link)(nil), "link.Link")
	proto.RegisterType((*Links)(nil), "link.Links")
}

func init() { proto.RegisterFile("pkg/link/link.proto", fileDescriptor_16115bece156ada2) }

var fileDescriptor_16115bece156ada2 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4f, 0x85, 0x30,
	0x14, 0xc5, 0x53, 0xe9, 0x33, 0xbe, 0xfb, 0x16, 0x53, 0x97, 0x86, 0x41, 0x09, 0x8b, 0x4c, 0x25,
	0xc1, 0xc9, 0x91, 0xdd, 0x89, 0xb8, 0x9b, 0x02, 0x15, 0x1a, 0xfe, 0xb4, 0x69, 0xcb, 0xd7, 0xf3,
	0xb3, 0x99, 0x5e, 0xc0, 0xd5, 0xa5, 0x39, 0x3d, 0x3d, 0xa7, 0xf9, 0xdd, 0x0b, 0x4f, 0x76, 0x1a,
	0xca, 0x59, 0xaf, 0x13, 0x1e, 0xc2, 0x3a, 0x13, 0x0c, 0xa3, 0x51, 0xa7, 0x2f, 0x83, 0x31, 0xc3,
	0xac, 0x4a, 0xf4, 0xda, 0xed, 0xbb, 0x0c, 0x7a, 0x51, 0x3e, 0xc8, 0xc5, 0xee, 0xb1, 0xfc, 0x87,
	0x00, 0xfd, 0xd0, 0xeb, 0xc4, 0x1e, 0x21, 0xd9, 0xdc, 0xcc, 0x49, 0x46, 0x8a, 0x6b, 0x13, 0x25,
	0x63, 0x40, 0x47, 0xe9, 0x47, 0x7e, 0x87, 0x16, 0x6a, 0x96, 0xc2, 0x43, 0xaf, 0x7c, 0xe7, 0x74,
	0xab, 0x78, 0x82, 0xfe, 0xdf, 0x9d, 0xbd, 0x03, 0x74, 0x4e, 0xc9, 0xa0, 0xfa, 0x2f, 0x19, 0x38,
	0xcd, 0x48, 0x71, 0xab, 0x52, 0xb1, 0x03, 0x88, 0x13, 0x40, 0x7c, 0x9e, 0x00, 0xcd, 0xf5, 0x48,
	0xd7, 0x21, 0x56, 0x37, 0xdb, 0x9f, 0xd5, 0xcb, 0xff, 0xd5, 0x23, 0x5d, 0x87, 0xfc, 0x15, 0x2e,
	0x91, 0xdf, 0xb3, 0x67, 0xc0, 0x91, 0x39, 0xc9, 0x92, 0xe2, 0x56, 0x81, 0xc0, 0x5d, 0xc4, 0xa7,
	0x06, 0xfd, 0xf6, 0x1e, 0xff, 0x79, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x33, 0x90, 0xfb, 0x81,
	0x2e, 0x01, 0x00, 0x00,
}
