// SESSION FETCH
export const SESSION_FETCH_REQUESTED = 'SESSION_FETCH_REQUESTED'
export const SESSION_FETCH_SUCCEEDED = 'SESSION_FETCH_SUCCEEDED'
export const SESSION_FETCH_FAILED = 'SESSION_FETCH_FAILED'

// SESSION CREATE
export const SESSION_CREATE_REQUESTED = 'SESSION_CREATE_REQUESTED'
export const SESSION_CREATE_SUCCEEDED = 'SESSION_CREATE_SUCCEEDED'
export const SESSION_CREATE_FAILED = 'SESSION_CREATE_FAILED'
