{
 "title": "gRPC metrics",
 "description": "Service request",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "metadata-exporter" }
  ]
 },
 "panels": [
  {
   "title": "request inbound rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$service\"}[1m])) by (grpc_service)"
    }
   ]
  },
  {
   "title": "unary request error percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$service\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)\n / \nsum(rate(grpc_server_started_total{job=\"$service\",grpc_type=\"unary\"}[1m])) by (grpc_service)\n * 100.0"
    }
   ]
  },
  {
   "title": "percentage of slow unary queries (>250ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$service\",grpc_type=\"unary\",le=\"0.25\"}[5m])) by (grpc_service)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$service\",grpc_type=\"unary\"}[5m])) by (grpc_service)\n) * 100.0"
    }
   ]
  },
  {
   "title": "unary request error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$service\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)"
    }
   ]
  },
  {
   "title": "average response stream size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{job=\"$service\",grpc_type=\"server_stream\"}[10m])) by (grpc_service)\n /\nsum(rate(grpc_server_started_total{job=\"$service\",grpc_type=\"server_stream\"}[10m])) by (grpc_service)"
    }
   ]
  }
 ]
}