{
 "title": "Base logger dashboard",
 "tags": [ "logger" ],
 "time": { "from": "2020-08-18T04:12:12.262Z", "to": "2020-08-18T16:12:12.262Z" },
 "templating": {
  "list": [
   { "name": "service_name", "label": "service_name", "query": "grafana,mongodb,loki" }
  ]
 },
 "panels": [
  {
   "title": "stderr total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"${service_name}\",source=\"stderr\"}[5m])",
     "legendFormat": "stderr"
    }
   ]
  },
  {
   "title": "stdout total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"${service_name}\",source=\"stdout\"}[5m])",
     "legendFormat": "stderr"
    }
   ]
  },
  {
   "title": "Fulllogs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{compose_service=\"${service_name}\"}",
     "legendFormat": "Service name"
    }
   ]
  }
 ]
}