// Code generated by mockery v2.36.0. DO NOT EDIT.

package v1

import mock "github.com/stretchr/testify/mock"

// MockisCheckDebugTrace_Resolution is an autogenerated mock type for the isCheckDebugTrace_Resolution type
type MockisCheckDebugTrace_Resolution struct {
	mock.Mock
}

type MockisCheckDebugTrace_Resolution_Expecter struct {
	mock *mock.Mock
}

func (_m *MockisCheckDebugTrace_Resolution) EXPECT() *MockisCheckDebugTrace_Resolution_Expecter {
	return &MockisCheckDebugTrace_Resolution_Expecter{mock: &_m.Mock}
}

// isCheckDebugTrace_Resolution provides a mock function with given fields:
func (_m *MockisCheckDebugTrace_Resolution) isCheckDebugTrace_Resolution() {
	_m.Called()
}

// MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isCheckDebugTrace_Resolution'
type MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call struct {
	*mock.Call
}

// isCheckDebugTrace_Resolution is a helper method to define mock.On call
func (_e *MockisCheckDebugTrace_Resolution_Expecter) isCheckDebugTrace_Resolution() *MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call {
	return &MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call{Call: _e.mock.On("isCheckDebugTrace_Resolution")}
}

func (_c *MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call) Run(run func()) *MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call) Return() *MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call) RunAndReturn(run func()) *MockisCheckDebugTrace_Resolution_isCheckDebugTrace_Resolution_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockisCheckDebugTrace_Resolution creates a new instance of MockisCheckDebugTrace_Resolution. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockisCheckDebugTrace_Resolution(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockisCheckDebugTrace_Resolution {
	mock := &MockisCheckDebugTrace_Resolution{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
