"""CRUD Referral use case."""

from domain.referral.v1.referral_pb2 import Referral as ReferralModel, Referrals as ReferralsModel

class CRUDReferralService:
  def __init__(self) -> None: ...

  def create(self, referral: ReferralModel) -> ReferralModel: ...

  def get(self, referral_id: str) -> ReferralModel: ...

  def update(self, referral: ReferralModel) -> ReferralModel: ...

  def delete(self, referral_id: str) -> None: ...

  def list(self, limit: int, offset: int) -> ReferralsModel: ...

