// Code generated by protoc-gen-go-orm. DO NOT EDIT.
// versions:
// - protoc-gen-go-orm v1.0.0
// - protoc             (unknown)
// source: domain/link_cqrs/v1/link.proto

package v1

type FilterLinkView struct {
	FieldMask       *StringFilterInput `json:"fieldmask"`
	Url             *StringFilterInput `json:"url"`
	Hash            *StringFilterInput `json:"hash"`
	Describe        *StringFilterInput `json:"describe"`
	ImageUrl        *StringFilterInput `json:"imageurl"`
	MetaDescription *StringFilterInput `json:"metadescription"`
	MetaKeywords    *StringFilterInput `json:"metakeywords"`
	CreatedAt       *StringFilterInput `json:"createdat"`
	UpdatedAt       *StringFilterInput `json:"updatedat"`
	Pagination      *Pagination        `json:"pagination,omitempty"`
}

type FilterLinksView struct {
	Pagination *Pagination `json:"pagination,omitempty"`
}
