{
 "title": "Unit economics",
 "description": "Unit economics refers to a company's revenues and costs related to an individual unit of production. A unit is simply one separate, quantifiable element that the company can create and sell and that adds value to both customers and the business.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User",
   "type": "stat",
   "description": "Пользователь — базовая сущность, определяет с чем мы работаем, в общем случае представляет из себя человека, который познакомился с нашим продуктом с помощью рекламы. Например, посетитель сайта для интернет-проектов или компания, в которую мы позвонили при холодных продажах, фактически речь идет о карточке в CRM.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 as total_count;\n" }
   ]
  },
  {
   "title": "User acquisition (UA)",
   "type": "stat",
   "description": "Число привлеченных пользователей. Показывает, сколько пользователей мы ознакомили с нашим продуктом посредством маркетинга. Например, сколько посетителей пришло на сайт с помощью контекстной рекламы или сколько компаний мы обзвонили при холодном обзвоне.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 as total_count;\n" }
   ]
  },
  {
   "title": "Conversion to first purchase (C1)",
   "type": "stat",
   "description": "Коэффициент конверсии из пользователя в клиента, первая покупка как раз отделяет простого пользователя, от пользователя, который совершил свою первую покупку и стал клиентом.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 as total_count;\n" }
   ]
  },
  {
   "title": "Buyer (B)",
   "type": "stat",
   "description": "Клиент, число клиентов, которые мы получаем с потока пользователей с учетом имеющегося коэффициента конверсии. B = UA x C1",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 as total_count;\n" }
   ]
  },
  { "title": "Price", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average Price (AvP)",
   "type": "stat",
   "description": "Средний чек — сумма, которую заплатил наш клиент оплачивая наши товары или услуги.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Cost of Good Sold (COGS)",
   "type": "stat",
   "description": "Себестоимость продажи, важная величина, показывает наши затраты, которые мы несем на каждой продаже. Важно отделять постоянные расходы, которые мы несем независимо от того есть у нас продажи или нет, от обязательных расходов, которые мы несем именно на каждой продаже. Например, если мы продаем товар, то COGS будет включать в себя затраты на покупку товара. Для b2b продаж, COGS может включать премию, которую мы выплачиваем с каждой продажи нашему менеджеру по продажам.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 10 as total_count;\n" }
   ]
  },
  {
   "title": "First sale COGS (1sCOGS)",
   "type": "stat",
   "description": "Дополнительные расходы, которые мы несем на самую первую продажу. Важно понимать, что это дополнительные расходы к COGS. Примером таких расходов могут являться затраты на проведение пилотов и интеграций для корпоративных клиентов, либо выплата повышенной комиссии нашему агенту по продажам.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Average Payment Count (APC)",
   "type": "stat",
   "description": "Среднее число платежей совершаемое одним клиентом за выбранный период. По умолчанию считается за все время жизни. Важно аккуратно относиться к расчету данной величины, и ее нельзя округлять ни в коем случае.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Gross Profit Margin (GPM)",
   "type": "stat",
   "description": "Величина характеризующая долю расходов на продажу (COGS) в общем обороте. Рассчитывается по формуле GPM = CM / Revenue",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 as total_count;\n" }
   ]
  },
  {
   "title": "Average Revenue per User (ARPU)",
   "type": "stat",
   "description": "Средний доход на одного пользователя. Характеризует получаемый нами доход с каждого пользователя, без учета затрат на маркетинг. Вычисляется по формуле ARPU = ARPC x C1. Важная величина для оценки эффективности бизнеса, сравнивая ее с CPA, можно получить оценку возврата маркетинговых инвестиций.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Customer Acquisition Cost (CAC)",
   "type": "stat",
   "description": "Стоимость привлечения клиента. Учитывает все затраты, которые мы понесли на получения клиента, например, мы делите весь ваш маркетинговый бюджет на всех полученных клиентов.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Cost per Acquisition (CPA)",
   "type": "stat",
   "description": "Стоимость привлечения одного пользователя. Рассчитывается путем деления всего маркетингового бюджета на всех пользователей. В отличие от CAC, CPA является метрикой принятия решения, так как не зависит от других метрик, таких как конверсия или величина потока пользователей.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Acquisition Cost (AC)",
   "type": "stat",
   "description": "Маркетинговый бюджет, все затраты на привлечение потока пользователей.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Contribution Margin (CM)",
   "type": "stat",
   "description": "Маржинальная прибыль на нашем потоке пользователей. Показывает, на сколько хорошо мы продаем наш товар или услугу. Основная величина, определяющая эффективность принимаемых нами решений. Вычисляется по формуле CM = UA x (ARPU — CPA) = UA x (ARPC x C1 — CPA)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "description": "Оборот от продажи товаров или услуг. Вычисляется по формуле Revenue = B x AvP x APC",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Return on Marketing Investment (ROMI)",
   "type": "stat",
   "description": "Возврат маркетинговых инвестиций, показывает насколько эффективно мы отработали свой маркетинговый бюджет. Вычисляется по формуле ROMI = CM / AC",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Average Revenue per Customer (ARPC)",
   "type": "stat",
   "description": "Средний доход на одного клиента. Показывает, сколько мы зарабатываем с продаж, совершенных клиентом за выбранный период, без учета затрат на маркетинг Рассчитывается по формуле ARPC = (AvP — COGS) x APC — 1sCOGS. Важная величина для оценки эффективности бизнеса, сравнивая ее с CAC, можно получить оценку возврата маркетинговых инвестиций.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "User acquisition for lead (UAL)",
   "type": "stat",
   "description": "Поток привлеченных пользователей, для смешанной модели. Данные пользователи конвертируются не в клиентов, а в лидов, которые мы потом продаем клиентам.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Conversion for lead (CL)",
   "type": "stat",
   "description": "Коэффициент конверсии пользователя в лида.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 50 as total_count;\n" }
   ]
  },
  {
   "title": "Leads",
   "type": "stat",
   "description": "Число лидов, которые мы продаем.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 as total_count;\n" }
   ]
  },
  {
   "title": "Sale Price (SP)",
   "type": "stat",
   "description": "Цена продажи лида.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Number of Sale (NS)",
   "type": "stat",
   "description": "Сколько раз мы можем продать лид. В некоторых моделях, можно продать лид нескольким покупателям и заработать дополнительные деньги.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 1 as total_count;\n" }
   ]
  },
  {
   "title": "Average Payment Count for lead (APCL)",
   "type": "stat",
   "description": "Среднее число обращений лида за услугой.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 5 as total_count;\n" }
   ]
  },
  {
   "title": "Cost Per Acquisition for lead (CPAL)",
   "type": "stat",
   "description": "Затраты на привлечение пользователя, которого будем превращать в лида.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  },
  {
   "title": "Acquisition Cost for lead (ACL)",
   "type": "stat",
   "description": "Маркетинговый бюджет на привлечение поток пользователей, которые будут превращены в лиды.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 10000 as total_count;\n" }
   ]
  },
  {
   "title": "Inventory Release (IR)",
   "type": "stat",
   "description": "Процент выкупа лидов. В некоторых ситуациях, мы не можем продать все лиды, которые мы получили.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 5 as total_count;\n" }
   ]
  },
  {
   "title": "Cost of Good Sold for lead (COGSL)",
   "type": "stat",
   "description": "Затраты на покупку лидов, которые покупает наш клиент.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 100 as total_count;\n" }
   ]
  }
 ]
}