{
 "title": "Argo CD Image Updater",
 "description": "Example dashboard for Argo CD Image Updater metrics",
 "tags": [ "argo cd" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of applications watched",
   "type": "timeseries",
   "description": "The total number of applications watched by Argo CD Image Updater",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_image_updater_applications_watched_total)",
     "legendFormat": "Applications"
    }
   ]
  },
  {
   "title": "Number of images watched",
   "type": "timeseries",
   "description": "Total number of images watched for updates by Argo CD Image Updater",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_image_updater_images_watched_total)",
     "legendFormat": "Images"
    }
   ]
  },
  {
   "title": "Image updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Image updates (total)",
   "type": "timeseries",
   "description": "The total number and error of images updated at a given time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_image_updater_images_updated_total[1m]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(increase(argocd_image_updater_images_updated_error_total[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Image updates (per app)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (application) (increase(argocd_image_updater_images_updated_total[5m]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Operational metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Registry API requests",
   "type": "timeseries",
   "description": "Number of API requests to registries in a specific time frame",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (registry) (increase(argocd_image_updater_registry_requests_total[1m]))",
     "legendFormat": "{{registry}} | requests"
    },
    {
     "expr": "sum by (registry) (increase(argocd_image_updater_registry_requests_failed_total[1m]))",
     "legendFormat": "{{registry}} | errors"
    }
   ]
  },
  {
   "title": "Argo CD API requests",
   "type": "timeseries",
   "description": "The number of requests to the Argo CD API server over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_image_updater_argocd_api_requests_total[1m]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(increase(argocd_image_updater_argocd_api_errors_total[1m]))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}