allowBuilds:
  '@datadog/pprof': true
  '@prisma/client': true
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  prisma: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true

provenance: true
saveExact: true
