{
 "title": "PGBouncer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "ccp_datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(ccp_pgbouncer_pools_client_active, cluster_name)"
    }
   },
   {
    "name": "pgbouncer_target_host",
    "query": {
     "query": "label_values(ccp_pgbouncer_pools_client_active{cluster_name=~\"[[cluster_name]]\"}, pgbouncer_target_host)"
    }
   },
   {
    "name": "conn_pool",
    "label": "Connection Pool",
    "query": {
     "query": "label_values(ccp_pgbouncer_pools_client_active{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"}, conn_pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connection % Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ccp_pgbouncer_databases_db_conn_perc_used{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"}",
     "legendFormat": "{{pool_db}}"
    }
   ]
  },
  {
   "title": "PGBouncer Total State Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ccp_pgbouncer_pools_client_active{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"})",
     "legendFormat": "client_active"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_client_waiting{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"})",
     "legendFormat": "client_waiting"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_active{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"})",
     "legendFormat": "server_active"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_idle{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"})",
     "legendFormat": "server_idle"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_used{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"})",
     "legendFormat": "server_used"
    }
   ]
  },
  {
   "title": "PGBouncer Item Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ccp_pgbouncer_lists_item_count{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Client Connection Counts Per Pool - [[cluster_name]] - [[pgbouncer_target_host]] - [[conn_pool]]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ccp_pgbouncer_clients_client_state_count{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\", conn_pool=\"[[conn_pool]]\"}",
     "legendFormat": "{{client_state}}"
    }
   ]
  },
  {
   "title": "Server Connection Counts Per Pool - [[cluster_name]] - [[pgbouncer_target_host]] - [[conn_pool]]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ccp_pgbouncer_servers_server_state_count{cluster_name=~\"[[cluster_name]]\",pgbouncer_target_host=~\"[[pgbouncer_target_host]]\", conn_pool=\"[[conn_pool]]\"}",
     "legendFormat": "{{server_state}}"
    }
   ]
  }
 ]
}