name: Fossa

on:
  push:
    branches:
      - main  # Set a branch to deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  fossa-scan:
    if: github.repository == 'shortlink-org/shortlink'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: fossas/fossa-action@c414b9ad82eaad041e47a7cf62a4f02411f427a0 # main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
